import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { Download, Lock, CheckCircle, AlertTriangle, TrendingUp, TrendingDown, X, ArrowRight, RefreshCw, Upload, ClipboardList, CreditCard, Shield } from 'lucide-react'
import AppNav from '../components/AppNav'
import { jsPDF } from 'jspdf'
import { credit } from '../lib/api'
import { encryptReport, decryptInputs } from '../lib/crypto'
import { toast } from '../hooks/useToast'
import type { Report, FeatureVector } from '../types'
import ScoreGauge from '../components/ScoreGauge'
import TierBadge from '../components/TierBadge'
import FactorCard from '../components/FactorCard'
import { analyseReport } from '../lib/scoreAnalysis'

export default function ReportDetail() {
  const { id } = useParams<{ id: string }>()
  const nav = useNavigate()
  const [report, setReport] = useState<Report | null>(null)
  const [encryptModal, setEncryptModal] = useState(false)
  const [encryptPw, setEncryptPw] = useState('')
  const [encryptLoading, setEncryptLoading] = useState(false)
  const [decryptedInputs, setDecryptedInputs] = useState<Partial<FeatureVector> | null>(null)

  useEffect(() => {
    if (!id) return
    credit.report(id).then(r => {
      setReport(r)
      if (r.encrypted_inputs) {
        decryptInputs(r.encrypted_inputs).then(d => setDecryptedInputs(d as Partial<FeatureVector> | null))
      }
    }).catch(() => nav('/reports'))
  }, [id, nav])

  const exportJSON = () => {
    if (!report) return
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `zkcredit-${report.report_id}.json`
    a.click()
  }

  const exportPDF = () => {
    if (!report) return
    const doc = new jsPDF()
    const lh = 8

    doc.setFontSize(20)
    doc.text('ZKCredit — Credit Report', 20, 20)

    doc.setFontSize(10)
    doc.setTextColor(100)
    doc.text(`Report ID: ${report.report_id}`, 20, 32)
    doc.text(`Generated: ${new Date(report.generated_at).toLocaleString()}`, 20, 32 + lh)

    doc.setFontSize(14)
    doc.setTextColor(0)
    doc.text('Score Summary', 20, 52)

    doc.setFontSize(11)
    const rows: [string, string][] = [
      ['Credit Score', `${report.score} / 900`],
      ['Tier', report.tier_label],
      ['Loan Limit', `₹${report.loan_limit.toLocaleString('en-IN')}`],
      ['Interest Rate', report.interest_rate ?? '—'],
      ['Term', report.term_months ? `${report.term_months} months` : '—'],
    ]
    rows.forEach(([k, v], i) => {
      doc.setTextColor(100)
      doc.text(k, 20, 62 + i * lh)
      doc.setTextColor(0)
      doc.text(v, 90, 62 + i * lh)
    })

    doc.setFontSize(14)
    doc.setTextColor(0)
    doc.text('Score Breakdown', 20, 108)

    doc.setFontSize(11)
    const breakdown: [string, string][] = [
      ['Payment History (max 35)', `${report.breakdown.payment_pts} pts`],
      ['FOIR (max 25)', `${report.breakdown.foir_pts} pts`],
      ['Credit History (max 15)', `${report.breakdown.history_pts} pts`],
      ['Credit Mix (max 15)', `${report.breakdown.credit_mix_pts} pts`],
      ['Enquiries (max 10)', `${report.breakdown.inquiry_pts} pts`],
      ['Adjustment', `${report.breakdown.adjustment > 0 ? '+' : ''}${report.breakdown.adjustment} pts`],
    ]
    breakdown.forEach(([k, v], i) => {
      doc.setTextColor(100)
      doc.text(k, 20, 118 + i * lh)
      doc.setTextColor(0)
      doc.text(v, 130, 118 + i * lh)
    })

    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text('Generated by ZKCredit — zero-knowledge credit scoring on Midnight blockchain', 20, 280)

    doc.save(`zkcredit-${report.report_id}.pdf`)
    toast('PDF downloaded', { variant: 'success' })
  }

  const exportZKCert = () => {
    if (!report) return
    const doc = new jsPDF()
    const lh = 9

    doc.setFillColor(10, 10, 10)

    doc.setFontSize(18)
    doc.setTextColor(20)
    doc.text('Zero-Knowledge Credit Certificate', 20, 24)

    doc.setFontSize(9)
    doc.setTextColor(120)
    doc.text('Issued by ZKCredit · Midnight Blockchain · Preprod Network', 20, 33)
    doc.text(`Report ID: ${report.report_id}`, 20, 33 + lh)
    doc.text(`Issued: ${new Date(report.generated_at).toLocaleString()}`, 20, 33 + lh * 2)

    doc.setFontSize(12)
    doc.setTextColor(20)
    doc.text('Proven Without Disclosure', 20, 62)

    doc.setFontSize(10)
    doc.setTextColor(60)
    const certText = [
      `The holder of this certificate has cryptographically proven:`,
      ``,
      `  Credit Tier:    ${report.tier_label}`,
      `  Loan Eligible:  ${report.tier > 0 ? 'Yes' : 'No'}`,
      `  Max Loan:       ${report.tier > 0 ? '₹' + report.loan_limit.toLocaleString('en-IN') : 'Not eligible'}`,
      `  Term:           ${report.term_months ? report.term_months + ' months' : '—'}`,
      `  Interest Rate:  ${report.interest_rate ?? '—'}`,
    ]
    certText.forEach((line, i) => {
      doc.text(line, 20, 73 + i * lh)
    })

    doc.setFontSize(10)
    doc.setTextColor(20)
    doc.text('What This Proof Does NOT Reveal', 20, 140)

    doc.setFontSize(9)
    doc.setTextColor(100)
    const hidden = [
      '  ✕  Exact credit score (300–900)',
      '  ✕  Monthly income or EMI obligations',
      '  ✕  Payment history or DPD records',
      '  ✕  Bank account details or identity',
      '  ✕  Any other personal financial data',
    ]
    hidden.forEach((line, i) => {
      doc.text(line, 20, 150 + i * lh)
    })

    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text('This certificate was generated using zero-knowledge proofs on the Midnight blockchain.', 20, 215)
    doc.text('The lender verifies only the tier commitment — the borrower\'s full credit profile remains private.', 20, 223)
    doc.text('Generated by ZKCredit — confidential credit scoring powered by Midnight.', 20, 231)

    doc.save(`zkcredit-zk-cert-${report.report_id}.pdf`)
    toast('ZK Certificate downloaded', { variant: 'success' })
  }

  const exportEncrypted = async () => {
    if (!report || !encryptPw) return
    setEncryptLoading(true)
    try {
      const encrypted = await encryptReport(report, encryptPw)
      const blob = new Blob([encrypted], { type: 'application/json' })
      const a = document.createElement('a')
      a.href = URL.createObjectURL(blob)
      a.download = `zkcredit-${report.report_id}.enc.json`
      a.click()
      toast('Encrypted report downloaded', { description: 'Keep your password safe — it cannot be recovered.', variant: 'success' })
      setEncryptModal(false)
      setEncryptPw('')
    } catch {
      toast('Encryption failed', { variant: 'error' })
    } finally {
      setEncryptLoading(false)
    }
  }

  if (!report) return (
    <div className="page min-h-screen flex items-center justify-center">
      <div className="w-8 h-8 border-2 border-white/20 border-t-transparent rounded-full animate-spin" />
    </div>
  )

  const analysis = analyseReport(report.breakdown, decryptedInputs ?? undefined)

  const SOURCE_LABEL: Record<string, string> = { upload: 'Bank Upload', form: 'Manual Entry', pan: 'PAN Card' }

  return (
    <div className="page min-h-screen text-zinc-100">
      <AppNav back title={`Report · ${report.report_id}`} />

      <main className="max-w-2xl mx-auto px-8 py-12 space-y-6">

        {/* ── Score overview ── */}
        <div className="glass rounded-3xl p-8 flex flex-col items-center gap-4">
          <ScoreGauge score={report.score} tier={report.tier_label} size={180} />
          <TierBadge tier={report.tier_label} size="lg" />
          <p className="text-zinc-500 text-sm">{new Date(report.generated_at).toLocaleString()}</p>
        </div>

        {/* ── Export actions ── */}
        <div className="flex flex-wrap gap-2">
          <button onClick={exportPDF} className="flex items-center gap-1.5 text-sm text-zinc-400 hover:text-zinc-200 transition-colors px-3 py-1.5 rounded-lg hover:bg-white/5 border border-white/8">
            <Download size={13} /> PDF
          </button>
          <button onClick={exportZKCert} className="flex items-center gap-1.5 text-sm text-emerald-400/80 hover:text-emerald-300 transition-colors px-3 py-1.5 rounded-lg hover:bg-emerald-500/5 border border-emerald-500/20">
            <Shield size={13} /> ZK Certificate
          </button>
          <button onClick={() => setEncryptModal(true)} className="flex items-center gap-1.5 text-sm text-zinc-400 hover:text-zinc-200 transition-colors px-3 py-1.5 rounded-lg hover:bg-white/5 border border-white/8">
            <Lock size={13} /> Encrypted
          </button>
          <button onClick={exportJSON} className="flex items-center gap-1.5 text-sm text-zinc-400 hover:text-zinc-200 transition-colors px-3 py-1.5 rounded-lg hover:bg-white/5 border border-white/8">
            <Download size={13} /> JSON
          </button>
        </div>

        {/* ── Method tag ── */}
        <div className="flex items-center gap-2">
          <span className="text-xs text-zinc-400 bg-white/5 border border-white/8 rounded-full px-3 py-1.5">
            {SOURCE_LABEL[report.data_source] ?? report.data_source}
          </span>
          {report.data_source === 'form' && (
            <span className="text-xs text-amber-400/70 bg-amber-500/[0.06] border border-amber-500/15 rounded-full px-3 py-1.5">
              Simulation
            </span>
          )}
        </div>

        {/* ── Loan terms ── */}
        <div className="glass rounded-2xl divide-y divide-white/5">
          {[
            ['Loan limit', report.tier > 0 ? `₹${report.loan_limit.toLocaleString('en-IN')}` : 'Not eligible'],
            ['Interest rate', report.interest_rate ?? '—'],
            ['Term', report.term_months ? `${report.term_months} months` : '—'],
            ['Loan applied', report.loan_applied ? 'Yes' : 'No'],
            ...(report.loan_tx_hash ? [['TX hash', report.loan_tx_hash]] : []),
          ].map(([k, v]) => (
            <div key={k} className="flex justify-between px-6 py-4 text-sm">
              <span className="text-zinc-400">{k}</span>
              <span className="text-zinc-100 font-medium font-mono text-xs truncate max-w-48">{v}</span>
            </div>
          ))}
        </div>

        {/* ── Apply for loan ── */}
        {report.tier > 0 && !report.loan_applied && (
          <button
            onClick={() => nav('/loan/apply', { state: { report } })}
            className="btn-primary w-full flex items-center justify-center gap-2"
          >
            Apply for loan <ArrowRight size={15} />
          </button>
        )}

        {/* ── Adjustment note ── */}
        <div className="flex items-start gap-2 text-xs text-zinc-500 px-1">
          {report.breakdown.adjustment >= 0
            ? <TrendingUp size={12} className="text-emerald-500 shrink-0 mt-0.5" />
            : <TrendingDown size={12} className="text-red-400 shrink-0 mt-0.5" />
          }
          <span className="leading-relaxed">{analysis.adjustmentNote}</span>
        </div>

        {/* ── What's working ── */}
        {analysis.strengths.length > 0 && (
          <section>
            <div className="flex items-center gap-2 mb-4">
              <CheckCircle size={16} className="text-emerald-400" />
              <h2 className="font-semibold text-zinc-200">What worked in your favour</h2>
            </div>
            <div className="grid gap-3">
              {analysis.strengths.map(f => <FactorCard key={f.key} f={f} />)}
            </div>
          </section>
        )}

        {/* ── Needs improvement ── */}
        {analysis.weaknesses.length > 0 && (
          <section>
            <div className="flex items-center gap-2 mb-4">
              <AlertTriangle size={16} className="text-amber-400" />
              <h2 className="font-semibold text-zinc-200">Areas that pulled the score down</h2>
            </div>
            <div className="grid gap-3">
              {analysis.weaknesses.map(f => <FactorCard key={f.key} f={f} />)}
            </div>
          </section>
        )}

        {/* ── Recalculate ── */}
        <section>
          <div className="flex items-center gap-2 mb-3">
            <RefreshCw size={13} className="text-zinc-500" />
            <h2 className="font-semibold text-zinc-400 text-sm">Calculate with a different method</h2>
          </div>
          <div className="grid grid-cols-3 gap-3">
            {[
              { label: 'Bank Upload',  Icon: Upload,        mode: 'upload' },
              { label: 'Manual Entry', Icon: ClipboardList, mode: 'form'   },
              { label: 'PAN Card',     Icon: CreditCard,    mode: 'pan'    },
            ].map(({ label, Icon, mode }) => (
              <button
                key={mode}
                onClick={() => nav('/score', { state: { mode } })}
                className={`flex flex-col items-center gap-2 p-4 rounded-2xl border text-sm font-medium transition-colors
                  ${report.data_source === mode
                    ? 'border-white/20 bg-white/8 text-zinc-100'
                    : 'border-white/8 bg-white/3 text-zinc-400 hover:border-white/15 hover:text-zinc-200'
                  }`}
              >
                <Icon size={17} />
                <span className="text-center leading-tight text-xs">{label}</span>
                {report.data_source === mode && <span className="text-[10px] text-zinc-500">Current</span>}
              </button>
            ))}
          </div>
        </section>
      </main>

      {/* ── Encrypt modal ── */}
      {encryptModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center px-4 bg-black/60 backdrop-blur-sm">
          <div className="glass rounded-3xl p-8 max-w-sm w-full space-y-5">
            <div className="flex items-center justify-between">
              <h2 className="font-semibold text-zinc-100">Export encrypted report</h2>
              <button onClick={() => { setEncryptModal(false); setEncryptPw('') }} className="text-zinc-500 hover:text-zinc-300">
                <X size={18} />
              </button>
            </div>
            <p className="text-sm text-zinc-400">
              Your report will be encrypted with AES-256-GCM. Keep the password safe — it cannot be recovered.
            </p>
            <div>
              <label className="label">Encryption password</label>
              <input
                type="password"
                value={encryptPw}
                onChange={e => setEncryptPw(e.target.value)}
                placeholder="Choose a strong password"
                className="input-field"
                autoFocus
                onKeyDown={e => e.key === 'Enter' && exportEncrypted()}
              />
            </div>
            <div className="flex gap-3">
              <button onClick={() => { setEncryptModal(false); setEncryptPw('') }} className="btn-ghost flex-1">Cancel</button>
              <button
                onClick={exportEncrypted}
                disabled={!encryptPw || encryptLoading}
                className="btn-primary flex-1 disabled:opacity-50"
              >
                {encryptLoading ? 'Encrypting...' : 'Download'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
